on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches-ignore:
      - '*'
  workflow_run:
    workflows:
      - Pull Request Deploy
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          # create a review app
          command: review-apps:create
          git_remote_url: 'ssh://dokku@simgs.com.br:22/first-dokku'
          # specify a name for the review app
          review_app_name: review-app-${{ github.event.pull_request.number }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  trigger_deploy:
    runs-on: ubuntu-latest

    needs: deploy
    if: ${{ github.event_name == 'workflow_run' }}

    steps:
      - name: Trigger Deploy
        run: echo "Deploy triggered by workflow run"

  destroy_review_app:
    runs-on: ubuntu-latest
    # only run when a pull request is closed
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Destroy the review app
        uses: dokku/github-action@master
        with:
          # destroy a review app
          command: review-apps:destroy
          git_remote_url: 'ssh://dokku@simgs.com.br:22/first-dokku'
          # specify a name for the review app
          review_app_name: review-app-${{ github.event.pull_request.number }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
