on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches-ignore:
      - '*'
  workflow_run:
    workflows:
      - Pull Request Deploy
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          # Execute aqui os comandos para implantar o código em produção
          # ...

  trigger_deploy:
    runs-on: ubuntu-latest

    needs: deploy
    if: ${{ github.event_name == 'workflow_run' }}

    steps:
      - name: Trigger Deploy
        run: echo "Deploy triggered by workflow run"
